xtest: fix missing init of local variables
Fix build error report by GCC with trace like:

/path/to/optee_test/host/xtest/regression_4000.c:5154:6: error: ‘ptx_hash_size’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      ta_crypt_cmd_asymmetric_verify(c,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/path/to/optee_test/host/xtest/regression_6000.c:263:23: error: ‘obj’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  op.params[0].value.a = obj;
  ~~~~~~~~~~~~~~~~~~~~~^~~~~
/path/to/optee_test/host/xtest/regression_6000.c:1615:11: note: ‘obj’ was declared here
  uint32_t obj;
           ^~~

/path/to/optee_test/host/xtest/adbg/include/adbg.h:136:2: error: ‘count’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  Do_ADBG_ExpectBuffer(Case_p, __FILE__, __LINE__, \
  ^~~~~~~~~~~~~~~~~~~~
/path/to/optee_test/host/xtest/regression_6000.c:986:11: note: ‘count’ was declared here
  uint32_t count;
           ^~~~~